# docker-compose.yml
version: "3.8"
services:
  php:
    build: ./php
    volumes:
      - ./src:/var/www
    env_file:
      - .env
  nginx:
    image: nginx:1.18-alpine
    ports:
      - 8888:80
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir:
      /var/www
    env_file:
    - .env
    depends_on:
      - php